/**
 * Canonical role keys — a GOVERNANCE CONTRACT owned by Agent 1 (Foundation).
 *
 * Adding or removing a RoleKey affects every workstream, so it requires a
 * CONTRACT_CHANGE_REQUEST. Workstreams do NOT edit this file to grant
 * permissions — they declare grants in their own `permissions.<workstream>.ts`
 * file (see `roleGrants`), which the barrel merges here at build time.
 *
 * This is a leaf module (no imports from the permission catalog) so the
 * per-workstream permission files can import `RoleKey` without a circular
 * dependency through the barrel.
 */
export const RoleKey = {
  ADMIN: 'ADMIN',
  RECEPTION: 'RECEPTION',
  NURSE: 'NURSE',
  DOCTOR: 'DOCTOR',
  PHARMA_REP: 'PHARMA_REP',
} as const;

export type RoleKey = (typeof RoleKey)[keyof typeof RoleKey];

export const ROLE_DESCRIPTIONS: Record<RoleKey, string> = {
  [RoleKey.ADMIN]: 'Clinic administrator — full operational access',
  [RoleKey.RECEPTION]: 'Front desk — registration, identification, check-in, queue',
  [RoleKey.NURSE]: 'Nursing/intake — identification, intake, queue',
  [RoleKey.DOCTOR]: 'Physician — clinical read access and queue',
  [RoleKey.PHARMA_REP]: 'Pharma field representative — NO patient/clinical access',
};

/**
 * Shape each workstream's permission module exports so the barrel can merge
 * them uniformly: the permission constants, their descriptions, and which
 * existing roles receive them.
 */
export interface WorkstreamPermissions {
  /** `{ CONST_NAME: 'resource:action' }` */
  permissions: Record<string, string>;
  /** `{ 'resource:action': 'human description' }` */
  descriptions: Record<string, string>;
  /** Grants of these permissions to existing roles (ADMIN gets all automatically). */
  roleGrants: Partial<Record<RoleKey, string[]>>;
}
