/**
 * PHARMA / HCP / DRUG / INTELLIGENCE event types — owned by Agent 4.
 *
 * Domain facts for the pharma field product and the governed intelligence
 * layer. Event payloads follow the same rule as audit metadata: they carry
 * identifiers and shape, never patient-identifiable data — pharma events
 * describe HCP engagement and master-data changes only (§45).
 */
export const PharmaEventType = {
  // HCP / HCO master data
  HCP_CREATED: 'HCP_CREATED',
  HCP_UPDATED: 'HCP_UPDATED',
  HCP_VERIFIED: 'HCP_VERIFIED',
  HCP_MERGED: 'HCP_MERGED',
  HCO_CREATED: 'HCO_CREATED',
  HCP_AFFILIATION_CHANGED: 'HCP_AFFILIATION_CHANGED',

  // Drug / medication master
  MEDICATION_CREATED: 'MEDICATION_CREATED',
  MEDICATION_UPDATED: 'MEDICATION_UPDATED',
  MEDICATION_PRODUCT_CREATED: 'MEDICATION_PRODUCT_CREATED',
  MEDICATION_IMPORT_COMPLETED: 'MEDICATION_IMPORT_COMPLETED',

  // Territory & field force
  TERRITORY_CREATED: 'TERRITORY_CREATED',
  TERRITORY_ASSIGNED: 'TERRITORY_ASSIGNED',
  HCP_TARGETED: 'HCP_TARGETED',
  VISIT_PLANNED: 'VISIT_PLANNED',
  VISIT_COMPLETED: 'VISIT_COMPLETED',
  VISIT_CANCELLED: 'VISIT_CANCELLED',
  CALL_REPORT_SUBMITTED: 'CALL_REPORT_SUBMITTED',
  SCIENTIFIC_REQUEST_CREATED: 'SCIENTIFIC_REQUEST_CREATED',
  SCIENTIFIC_REQUEST_ANSWERED: 'SCIENTIFIC_REQUEST_ANSWERED',
  FOLLOW_UP_CREATED: 'FOLLOW_UP_CREATED',
  FOLLOW_UP_COMPLETED: 'FOLLOW_UP_COMPLETED',

  // Approved scientific content
  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_WITHDRAWN: 'CONTENT_WITHDRAWN',
  CONTENT_ENGAGED: 'CONTENT_ENGAGED',

  // Segmentation & campaigns
  SEGMENT_CREATED: 'SEGMENT_CREATED',
  SEGMENT_MEMBER_ASSIGNED: 'SEGMENT_MEMBER_ASSIGNED',
  CAMPAIGN_CREATED: 'CAMPAIGN_CREATED',
  CAMPAIGN_TARGET_ADDED: 'CAMPAIGN_TARGET_ADDED',

  // Healthcare intelligence (firewall outcomes are themselves domain facts)
  INTELLIGENCE_RUN_COMPLETED: 'INTELLIGENCE_RUN_COMPLETED',
  INTELLIGENCE_SIGNAL_PUBLISHED: 'INTELLIGENCE_SIGNAL_PUBLISHED',
  INTELLIGENCE_COHORT_SUPPRESSED: 'INTELLIGENCE_COHORT_SUPPRESSED',
} as const;
