/**
 * Platform-level UI strings only (shell, auth, shared states). Domain teams
 * (Agents 2/3/4) add their own namespaced dictionaries and merge them via
 * `registerMessages` — they do NOT edit this file, avoiding merge conflicts.
 */
export type Locale = 'en' | 'ar';
export type Direction = 'ltr' | 'rtl';

export const LOCALES: Record<Locale, { label: string; dir: Direction }> = {
  en: { label: 'English', dir: 'ltr' },
  ar: { label: 'العربية', dir: 'rtl' },
};

export type Messages = Record<string, string>;

export const platformMessages: Record<Locale, Messages> = {
  en: {
    'app.name': 'MEDCORE',
    'nav.dashboard': 'Dashboard',
    'auth.signIn': 'Sign in',
    'auth.clinicId': 'Clinic ID',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.signOut': 'Sign out',
    'auth.signingIn': 'Signing in…',
    'auth.failed': 'Sign in failed. Check your credentials.',
    'common.loading': 'Loading…',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.page': 'Page',
    'common.of': 'of',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'state.empty.title': 'Nothing here yet',
    'state.empty.body': 'There is no data to show.',
    'state.error.title': 'Something went wrong',
    'error.forbidden.title': 'Access denied',
    'error.forbidden.body': 'You do not have permission to view this.',
    'error.notFound.title': 'Page not found',
    'error.notFound.body': 'The page you requested does not exist.',
    'lang.toggle': 'العربية',
  },
  ar: {
    'app.name': 'مِدكور',
    'nav.dashboard': 'لوحة التحكم',
    'auth.signIn': 'تسجيل الدخول',
    'auth.clinicId': 'معرّف العيادة',
    'auth.username': 'اسم المستخدم',
    'auth.password': 'كلمة المرور',
    'auth.signOut': 'تسجيل الخروج',
    'auth.signingIn': 'جارٍ تسجيل الدخول…',
    'auth.failed': 'فشل تسجيل الدخول. تحقق من بياناتك.',
    'common.loading': 'جارٍ التحميل…',
    'common.retry': 'إعادة المحاولة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.close': 'إغلاق',
    'common.search': 'بحث',
    'common.page': 'صفحة',
    'common.of': 'من',
    'common.previous': 'السابق',
    'common.next': 'التالي',
    'state.empty.title': 'لا يوجد شيء بعد',
    'state.empty.body': 'لا توجد بيانات للعرض.',
    'state.error.title': 'حدث خطأ ما',
    'error.forbidden.title': 'تم رفض الوصول',
    'error.forbidden.body': 'ليس لديك إذن لعرض هذا.',
    'error.notFound.title': 'الصفحة غير موجودة',
    'error.notFound.body': 'الصفحة المطلوبة غير موجودة.',
    'lang.toggle': 'English',
  },
};
